### PR TITLE
Add bmaptool and sd-mux-ctrl

### LINKED ISSUE #35: Please include bmaptool in meta-rte
**The problem you're addressing (if any)**
Lack of bmaptool needed by SDWire testing stand

**Describe the solution you'd like**
meta-rte should have bmaptool to flash the SD card for SDWire testing instead of relying on an old Armbian...

**Where is the value to a user, and who might that user be?**
No need to use dd over and over again. Bmaptool will detect quickly if it needs to flash anything on SD. Lesser SD wear out.

### PR DESCRIPTION
**Pull request by PLangowski**
This PR integrates changes from `v0.7.4-rc4`.

### CODE REVIEW

**Comment by tomzy-0** [comment]
@PLangowski looks good, I see it also adds sd-mux which is fine. Please change only the target branch to `develop`. I would rather merge everything to that, and then merge to main and make a release.

**Comment by tomzy-0** [comment]
@PLangowski now I see that we already have an PR with those changes. Why we created another PR?

**Comment by PLangowski** [comment]
@TomaszAIR Can you link the PR? I don't see one that's the same as this one.

**Comment by tomzy-0** [comment]
@PLangowski it is not PR but we have a branch with such changes and we could use it or at least you could mention that those commits were taken from different branch, in case we merge this we will also need to close/remove the other branch so we do not left any dangling branches with already merged changes.

**Comment by PLangowski** [comment]
@TomaszAIR I was asked to cherry-pick those commits from the `v0.7.4-rc4` tag, But if they're on that tag it means that they will be a part of the next release, right? In that case, if you don't want them merged to master immediately I guess this PR is pointless.

**Pull request closed without merging**
