### PR TITLE
Add meta-coreboot and meta-dasharo to meta-rte build,

### PR DESCRIPTION
**Pull request by Al-an-21**
drop coreboot-utils, and install dcu package.

### CODE REVIEW

**Comment by m-iwanicki** [comment]
`meta-rte` used `coreboot/coreboot` version after changes we are using `dasharo/coreboot` from `meta-coreboot`

**Comment by m-iwanicki** [comment]
@macpijan after changing to `dasharo/coreboot` I get errors when trying to build cbfstool:

`error: 'memcpy' specified bound between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]`

```
ERROR: cbfstool-4.21+git-r0 do_compile: oe_runmake failed
ERROR: cbfstool-4.21+git-r0 do_compile: ExecutionError('/build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/temp/run.do_compile.940', 1, None, None)
ERROR: Logfile of failure stored in: /build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/temp/log.do_compile.940
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 32 DESTDIR="/build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/image" PREFIX="/usr" -C util/cbfstool cbfstool
| make: Entering directory '/build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/util/cbfstool'
|     HOSTCC     cbfstool/cbfstool.o
|     HOSTCC     cbfstool/common.o
|     HOSTCC     cbfstool/cbfs_image.o
|     HOSTCC     cbfstool/cbfs-mkstage.o
|     HOSTCC     cbfstool/cbfs-mkpayload.o
|     HOSTCC     cbfstool/elfheaders.o
|     HOSTCC     cbfstool/rmodule.o
|     HOSTCC     cbfstool/xdr.o
|     HOSTCC     cbfstool/partitioned_file.o
|     HOSTCC     cbfstool/platform_fixups.o
|     HOSTCC     cbfstool/cbfs_private.o
|     HOSTCC     cbfstool/fsp_relocate.o
|     HOSTCC     cbfstool/fmap.o
|     HOSTCC     cbfstool/kv_pair.o
|     HOSTCC     cbfstool/valstr.o
|     HOSTCC     cbfstool/linux_trampoline.o
|     HOSTCC     cbfstool/cbfs-payload-linux.o
|     HOSTCC     cbfstool/compress.o
|     HOSTCC     cbfstool/lz4.o
|     HOSTCC     cbfstool/lz4hc.o
|     HOSTCC     cbfstool/lz4frame.o
|     HOSTCC     cbfstool/xxhash.o
|     HOSTCC     cbfstool/lz4_wrapper.o
|     HOSTCC     cbfstool/lzma.o
|     HOSTCC     cbfstool/LzFind.o
|     HOSTCC     cbfstool/LzmaDec.o
|     HOSTCC     cbfstool/LzmaEnc.o
|     MAKE       /build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/util/vboot_lib/libvboot_host.a
| make[1]: Entering directory '/build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/3rdparty/vboot'
| vboot SHA256 built with tight loops (slower, smaller code size)
|     CC            cgpt/cgpt_add.o
|     CC            cgpt/cgpt_boot.o
|     CC            cgpt/cgpt_common.o
|     CC            cgpt/cgpt_create.o
|     CC            cgpt/cgpt_edit.o
|     CC            cgpt/cgpt_find.o
|     CC            cgpt/cgpt_prioritize.o
|     CC            cgpt/cgpt_repair.o
|     CC            cgpt/cgpt_show.o
|     CC            firmware/2lib/2common.o
|     CC            firmware/2lib/2context.o
|     CC            firmware/2lib/2crc8.o
|     CC            firmware/2lib/2crypto.o
|     CC            firmware/2lib/2hmac.o
|     CC            firmware/2lib/2kernel.o
|     CC            firmware/2lib/2nvstorage.o
|     CC            firmware/2lib/2recovery_reasons.o
|     CC            firmware/2lib/2rsa.o
|     CC            firmware/2lib/2sha1.o
|     CC            firmware/2lib/2sha256.o
|     CC            firmware/2lib/2sha512.o
|     CC            firmware/2lib/2sha_utility.o
|     CC            firmware/2lib/2struct.o
|     CC            firmware/2lib/2stub.o
|     CC            firmware/2lib/2stub_hwcrypto.o
|     CC            firmware/lib/cgptlib/cgptlib_internal.o
|     CC            firmware/lib/cgptlib/crc32.o
|     CC            firmware/lib/gpt_misc.o
|     CC            firmware/stub/tpm_lite_stub.o
|     CC            firmware/stub/vboot_api_stub_disk.o
|     CC            futility/dump_kernel_config_lib.o
|     CC            host/arch/x86_64/lib/crossystem_arch.o
|     CC            host/lib/chromeos_config.o
|     CC            host/lib/crossystem.o
|     CC            host/lib/crypto.o
|     CC            host/lib/extract_vmlinuz.o
|     CC            host/lib/subprocess.o
|     CC            host/lib/cbfstool.o
|     CC            host/lib/fmap.o
|     CC            host/lib/host_misc.o
|     CC            host/lib21/host_misc.o
|     CC            firmware/lib/tpm_lite/tlcl.o
| host/lib/extract_vmlinuz.c: In function 'ExtractVmlinuz':
| host/lib/extract_vmlinuz.c:67:9: error: 'memcpy' specified bound between 2147483648 and 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overflow=]
|    67 |         memcpy(vmlinuz, kpart_data + vmlinuz_header_offset,
|       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|    68 |                vmlinuz_header_size);
|       |                ~~~~~~~~~~~~~~~~~~~~
| At top level:
| cc1: note: unrecognized command-line option '-Wno-unknown-warning' may have been intended to silence earlier diagnostics
| cc1: all warnings being treated as errors
| make[1]: *** [Makefile:1163: /build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/util/vboot_lib/host/lib/extract_vmlinuz.o] Error 1
| make[1]: *** Waiting for unfinished jobs....
| make[1]: Leaving directory '/build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/3rdparty/vboot'
| make: *** [Makefile.inc:155: /build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/util/vboot_lib/libvboot_host.a] Error 2
| make: *** Waiting for unfinished jobs....
| make: Leaving directory '/build/tmp/work/cortexa7t2hf-neon-rte-linux-gnueabi/cbfstool/4.21+git/git/util/cbfstool'
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/build/../work/meta-coreboot/recipes-bsp/coreboot-utils/cbfstool_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 834 tasks of which 827 didn't need to be rerun and 1 failed.
```

**Comment by m-iwanicki** [comment]
Added `fix` here: https://github.com/3mdeb/meta-rte/pull/84/commits/fcce00085620f6da10e3076ec64739b67e92122d
@krystian-hebel said that error might be due to treating some variable (maybe pointer?) as a signed value instead of unsigned.
Build completed successfully

**Review by macpijan — APPROVED** [review]
Looks ok but there are two pre-commit failures. If we do not like them, we can silence them or disable in config.

**Comment by m-iwanicki** [comment]
I moved fetching submodule via SRC_URI to `meta-coreboot`.
* https://github.com/3mdeb/meta-rte/compare/fcce00085620f6da10e3076ec64739b67e92122d..2e591bf658a46befce65db2ec17fd56a76027026
* https://github.com/zarhus/meta-coreboot/pull/2/commits/0ea7450cc86c530574ff928750467a7e3f3b095c

**Pull request merged**
